Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectrosLtdApplication.Models;
using Common;
using System.Net.Mail;

namespace ElectrosLtdApplication.Controllers
{
    public class ShoppingCartController : Controller
    {
        //
        // GET: /ShoppingCart/
        [Authorize(Roles = "User")]
        public ActionResult ShoppingCart()
        {
            OrderModel viewModel = new OrderModel();
            try
            {
                Order order = new Order();
                order = new OrderServ.OrderServiceClient().GetOrderByPersonId(User.Identity.Name);
                User u = new UserServ.UserServiceClient().getUserByUsername(User.Identity.Name);




                viewModel.OrderItem = order.OrderItem;

                // Set up our ViewModel
                //var viewModel = new OrderModel
                //{
                //    CartItems = cart.GetCartItems(),
                //    CartTotal = cart.GetTotal()
                //};

                // Return the view
                return View(viewModel);
            }
            catch (Exception e)
            {
                  ViewBag.Message = "Sorry there seems to be a problem"; 
                return View(viewModel);
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            try
            {
                // Remove the item from the cart

                Order order = new OrderServ.OrderServiceClient().GetOrderByPersonId(User.Identity.Name);


                OrderItem item = new OrderItemServ.OrderItemServiceClient().GetOrderItemById(id);
                //// Remove from cart
                //int itemCount = cart.RemoveFromCart(id);
                new OrderItemServ.OrderItemServiceClient().DeleteOrderItem(id);

                //// Display the confirmation message


                return Json(item.Product.Name + "has been removed");
            }
            catch (Exception e)
            {

                return Json("There seems to be a problem. Error :" + e.Message);
            }
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult UpdateFromCart(int id, string qty)
        {
            try
            {
                OrderItem oi = new OrderItem();
                if (id != null)
                {

                    oi = new OrderItemServ.OrderItemServiceClient().GetOrderItemById(id);

                    int txtQty = Convert.ToInt16(qty);
                    if (txtQty != 0)
                    {
                        if (oi.Product.Stock >= txtQty)
                        {
                            oi.Qty = txtQty;
                            new OrderItemServ.OrderItemServiceClient().UpdateOrderItem(oi);
                        }
                        else
                        {

                            return Json("Only " + oi.Product.Stock + " are left on stock");
                        }

                    }
                    else
                    {
                        new OrderItemServ.OrderItemServiceClient().DeleteOrderItem(oi.OrderId);

                    }

                }
                return Json(oi.Product.Name + "has been updated");
            }
            catch (Exception e)
            {
               
                return Json("Sorry there seems to be a problem");

            }

        }

        [Authorize(Roles = "User")]
        public ActionResult CheckOut()
        {
            Order order = new Order();
            OrderModel viewModel = new OrderModel();
            try
            {
                order = new OrderServ.OrderServiceClient().GetOrderByPersonId(User.Identity.Name);
                User u = new UserServ.UserServiceClient().getUserByUsername(User.Identity.Name);




                foreach (OrderItem oi in order.OrderItem)
                {
                    viewModel.Total += oi.Qty * oi.Product.Price;
                }


                viewModel.OrderItem = order.OrderItem;

                return View(viewModel);
            }
            catch (Exception e)
            {
                ViewBag.Message = "Sorry there seems to be a problem"; 
                return View(viewModel);

            }

        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult CheckOutAndPay()
        {
            try
            {

                Order o = new OrderServ.OrderServiceClient().GetOrderByPersonId(User.Identity.Name);

                if (o != null && o.IsPending != false)
                {
                    o.IsPending = false;
                    o.IsShipped = true;
                    o.DateTime = DateTime.Now;
                    new OrderServ.OrderServiceClient().ConfirmOrder(o);
                    //NAQAS QTYY



                  

                    User p = new UserServ.UserServiceClient().getUserByUsername(User.Identity.Name);


                    System.Net.Mail.MailMessage ms = new System.Net.Mail.MailMessage();
                    ms.Subject = o.OrderId.ToString();
                    ms.To.Add(p.Email);
                    ms.To.Add("websiteclem@gmail.com");
                    ms.Body = "Hi " + p.Username + "";

                    ms.Body += "<p>Order No: " + o.OrderId + " has been sucessfully ordered </p>";

                    ms.Body += "Thank you from ,Electros Team";
                    ms.IsBodyHtml = true;

                    SmtpClient cl = new SmtpClient();
                    cl.EnableSsl = true;
                    cl.Send(ms);

                    return Json("Order has been ordered");
                }

                return View();
            }
            catch (Exception e)
            {
                return Json("Sorry there seems to be a problem");
            }

        }
    }
}

Controllers/UpdateFaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using ElectrosLtdApplication.Models;
using System.Net.Mail;
using System.Web.UI.WebControls;
using System.Net;
using System.IO;

namespace ElectrosLtdApplication.Controllers
{
    public class UpdateFaultController : Controller
    {
        //
        // GET: /UpdateFault/
        [Authorize(Roles = "Admin")]
        public ActionResult ListAllFaults()
        {
            List<Fault> faults = new FaultServ.FaultServiceClient().GetAllFaults().ToList();

            List<SelectListItem> ls = new List<SelectListItem>();
            List<String> types = new List<string>();

            types.Add("Date ASC");
            types.Add("Date DES");



            foreach (var type in types)
            {
                ls.Add(new SelectListItem() { Text = type, Value = type });
            }
            ViewBag.ddl = ls;


            return View(faults);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public PartialViewResult FilterFault(string from, string to, string clientId, string faultId, string sort , string category)
        {
            List<FaultTrack> faultTrack  = new FaultTrackServ.FaultTrackServiceClient().GetAllFaultTracks().ToList();

            try
            {
                int? client = null;
                int? fault = null;

                if (clientId != "Select")
                {
                    client = Int32.Parse(clientId);
                }
                if (faultId != "Select")
                {
                    fault = Int32.Parse(faultId);
                }

                DateTime startDate;
                DateTime endDate;
                if (DateTime.TryParse(from, out startDate))
                {
                    if (DateTime.TryParse(to, out endDate))
                    {
                        if (endDate > startDate)
                        {

                            faultTrack = new FaultTrackServ.FaultTrackServiceClient().Filter(client, fault, startDate, endDate).ToList();
                        }
                    }

                }

                 if (sort == "Date ASC")
                {
                    faultTrack = faultTrack.OrderBy(t => t.Date).ToList();
                }
                else if (sort == "Date DES")
                {
                    faultTrack = faultTrack.OrderByDescending(t => t.Date).ToList();
                }

                if (category != "Select" && category != "")
                            {
                                int categoryId = Int32.Parse(category);

                               faultTrack = faultTrack.Where(c => c.Fault.OrderItem.Product.CategoryId == categoryId).ToList();

                            }


               return PartialView("_FilterListAllFaultTrack", faultTrack);
              //  return View("ListAllFaultTrack", faultTrack);
            }
            catch (Exception e)
            {
                ViewBag.Message = "Sorry there seems to be a problem"; 
                return PartialView("_FilterListAllFaultTrack", faultTrack);
            }
        }

        

        


       [Authorize(Roles = "Admin")]
       
        public ActionResult ListAllFaultTrack()
        {
            List<FaultTrack> faults = new List<FaultTrack>();
           
            try
            {
                faults = new FaultTrackServ.FaultTrackServiceClient().GetAllFaultTracks().ToList();
              

                List<SelectListItem> ls = new List<SelectListItem>();
                List<String> types = new List<string>();

                //types.Add("Price ASC");
                //types.Add("Price DES");
                types.Add("Date ASC");
                types.Add("Date DES");



                foreach (var type in types)
                {
                    ls.Add(new SelectListItem() { Text = type, Value = type });
                }
                ViewBag.ddl = ls;


                List<SelectListItem> category = new ProductServ.ProductServiceClient().GetAllCategory().Select(c => new SelectListItem
                {
                    Value = c.CategoryId.ToString(),
                    Text = c.Name.ToString(),
                    Selected = false
                }).ToList();


                ViewBag.Category = category;

                List<SelectListItem> users = new UserServ.UserServiceClient().GetAllUsers().Select(c => new SelectListItem
            {
                Value = c.UserId.ToString(),
                Text = c.UserId.ToString(),
                Selected = false
            }).ToList();


                ViewBag.Users = users;



                List<SelectListItem> items = new FaultServ.FaultServiceClient().GetAllFaults().Select(c => new SelectListItem
                {
                    Value = c.FaultId.ToString(),
                    Text = c.FaultId.ToString()
                }).ToList();
                ViewBag.Faults = items;


                return View("ListAllFaultTrack", faults);
            }
            catch (Exception e)
            {

                ViewBag.Message = "Sorry there seems to be a problem"; 
                return View("ListAllFaultTrack", faults);
            }
           
        }

        [Authorize(Roles = "Admin")]
        public ActionResult UpdateFault(int id)
        {
            FaultTrackModel faultTrack = new FaultTrackModel();
            try
            {


                faultTrack.FaultTrackList = new FaultTrackServ.FaultTrackServiceClient().GetFaultTracksByFaultId(id).ToList();
                faultTrack.FaultId = id;


                ViewBag.Status = new UserServ.UserServiceClient().getAllRoles();


                return View(faultTrack);
            }
            catch (Exception e)
            {

                ViewBag.Message = "Sorry there seems to be a problem"; 
                return View(faultTrack);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult UpdateFault(FaultTrackModel faultTrack)
        {
            FaultTrackModel ft = faultTrack;
            FaultTrack faultT = new FaultTrack();
            try
            {

                ft.FaultTrackList = new FaultTrackServ.FaultTrackServiceClient().GetFaultTracksByFaultId(faultTrack.FaultId).ToList();
              

                if (faultTrack.Description != null && faultTrack.Type != null) 
                {
                    faultT.Type = faultTrack.Type;
                    faultT.Date = DateTime.Now;
                    faultT.Description = faultTrack.Description;

                    faultT.FaultId = faultTrack.FaultId;



                    new FaultTrackServ.FaultTrackServiceClient().AddFaultTrack(faultT);

                    //User u = new UserServ.UserServiceClient().GetUserById(faultTrack.Fault.OrderItem.Order.UserId);
                    Fault fault = new FaultServ.FaultServiceClient().GetFaultById(faultTrack.FaultId);
                    OrderItem oi = new OrderItemServ.OrderItemServiceClient().GetOrderItemById(fault.OrderItemId);
                    Order o = new OrderServ.OrderServiceClient().GetOrderByOrderId(oi.OrderId);
                    User u = new UserServ.UserServiceClient().GetUserById(o.UserId);

                    MailMessage mail = new MailMessage();


                    mail.Subject = oi.OrderItemId.ToString();
                    mail.To.Add(u.Email);
                    mail.To.Add("websiteclem@gmail.com");
                    mail.IsBodyHtml = true;
                    mail.Body = "Hi " + u.Username + "";
                    mail.Body += "<p>Order Item No: " + oi.OrderItemId + "</p>";
                    mail.Body += "<p>Status: " + faultTrack.Type + "</p>";
                    mail.Body += "<p>Thank you from ,Electros Team</p>";

                    SmtpClient cl = new SmtpClient();
                    cl.EnableSsl = true;
                    cl.Send(mail);

                    // SmsServ.ClickatellSms sms = new SmsServ.ClickatellSms();
                    //amlu li ma ikunx null u zid 356
                    // String[] numTo = {u.Mobile.ToString()};
                    // String[] numTo = { "35679009492" };

                    //c92454769eb50ca96ae716332a30c52

                    //commented
                    // sms.sendmsg("", 3473164, true, "clementina", "OcPOfKPODFWTMg", "bla", numTo, "35679009492", 1, false, 0, false, 7, false, 7, true, 1, false, 1, false, 3, true, 0, true, 0, false,"3473164", 0, false, "SMS_TEXT", "Fault", "String", 1440, true);

                    //sms.sendmsg("", 3480167, true, "clemcass", "PFcKPRaLVCDWPZ", "bla", numTo, "35679009492", 1, false, 0, false, 7, false, 7, true, 1, false, 1, false, 3, true, 0, true, 0, false, "3473164", 0, false, "SMS_TEXT", "Fault", "String", 1440, true);

                    SmsServ.ClickatellSms sms = new SmsServ.ClickatellSms();
                    //amlu li ma ikunx null u zid 356
                    // String[] numTo = {u.Mobile.ToString()};
                    string num = "356" + u.Mobile.ToString();
                    String[] numTo = { num };

                    //c92454769eb50ca96ae716332a30c52
                    string message = "Hi just to inform you that your order item no :" + oi.OrderItemId + " is  " + faultTrack.Type;

                    //commented
                    //sms.sendmsg("", 3480178, true, "clementina", "OcPOfKPODFWTMg", message, numTo, "35679009492", 1, false, 0, false, 7, false, 7, true, 1, false, 1, false, 3, true, 0, true, 0, false, "3480178", 0, false, "SMS_TEXT", "Fault", "String", 1440, true);

                    WebClient clientSMS = new WebClient();
                    clientSMS.Headers.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
                    clientSMS.QueryString.Add("user", "clementina");

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Electros</title>
    <!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
			
		<![endif]-->
    <link rel="stylesheet" media="all" href="../../css/style.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->
    <!-- JS -->
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="../../js/Scripts/jquery-1.6.4.min.js"></script>
    <script src="../../js/Scripts/css3-mediaqueries.js"></script>
    <script src="../../js/Scripts/custom.js"></script>
    <script src="../../js/Scripts/tabs.js"></script>
    <!-- Tweet -->
    <link rel="stylesheet" href="../../css/jquery.tweet.css" media="all" />
    <script src="../../js/tweet/jquery.tweet.js"></script>
    <!-- ENDS Tweet -->
    <!-- superfish -->
    <link rel="stylesheet" media="screen" href="../../css/superfish.css" />
    <script src="../../js/superfish-1.4.8/js/hoverIntent.js"></script>
    <script src="../../js/superfish-1.4.8/js/superfish.js"></script>
    <script src="../../js/superfish-1.4.8/js/supersubs.js"></script>
    <!-- ENDS superfish -->
    <!-- prettyPhoto -->
    <script src="../../js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
    <link rel="stylesheet" href="../../js/prettyPhoto/css/prettyPhoto.css" media="screen" />
    <!-- ENDS prettyPhoto -->
    <!-- poshytip -->
    <link rel="stylesheet" href="../../js/poshytip-1.1/src/tip-twitter/tip-twitter.css" />
    <link rel="stylesheet" href="../../js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css" />
    <script src="../../js/poshytip-1.1/src/jquery.poshytip.min.js"></script>
    <!-- ENDS poshytip -->
    <!-- GOOGLE FONTS -->
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,300' rel='stylesheet'
        type='text/css'>
    <!-- Flex Slider -->
    <link rel="stylesheet" href="../../css/flexslider.css">
    <script src="../../js/jquery.flexslider-min.js"></script>
    <!-- ENDS Flex Slider -->
    <!-- Less framework -->
    <link rel="stylesheet" media="all" href="../../css/lessframework.css" />
    <!-- modernizr -->
    <script src="../../js/modernizr.js"></script>
    <!-- SKIN -->
    <link rel="stylesheet" media="all" href="../../css/skin.css" />
    <!-- reply move form -->
    <script src="../../js/moveform.js"></script>
</head>
<body lang="en">
    <header class="clearfix">
        <!-- top widget -->
        <!-- ENDS top-widget -->
        <div class="wrapper">
            <a href="index.html" id="logo">
                <img src="../../Images/electros.png" alt="Zeni"></a>
            <nav>
                <ul id="nav" class="sf-menu">
                    <li class="current-menu-item">@Html.ActionLink("Home", "Index", "Home")</li>
                    
                    <li>@Html.ActionLink("Product", "Products", "Product")</li>
                    @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("User"))
                    {
                    <li>@Html.ActionLink("Purchased History", "ItemsPurchased", "ItemsPurchased")</li>
                    <li>@Html.ActionLink("Fault", "ItemsPurchased", "ItemsPurchased")
                        <ul>
                                    <li>@Html.ActionLink("Purchased History", "AllItemsPurchased", "ManageReturnsFaults")</li>

                         </ul>
                    
                    </li>
                    }
                    @if ( Request.IsAuthenticated && HttpContext.Current.User.IsInRole( "Admin" ) )
                     {

                    <li>@Html.ActionLink("Admin", "ItemsPurchased", "ItemsPurchased")
                        <ul>
                            <li>@Html.ActionLink("Update Faults", "ListAllFaults", "UpdateFault")</li>
                            <li>@Html.ActionLink("List all Faults Tracks", "ListAllFaultTrack", "UpdateFault")</li>
                            <li>@Html.ActionLink("Reports", "Reports", "Reports")
                                <ul>
                                    <li>@Html.ActionLink("Highly Rated Item", "HighlyRatedItem", "Reports")</li>
                                    <li>@Html.ActionLink("Most Purchased Item", "MostPurchasedItem", "Reports")</li>
                                    <li>@Html.ActionLink("Highest NumberOfFaults", "HighestNumberOfFaults", "Reports")</li>
                                    <li>@Html.ActionLink("Lowest Number Of Faults", "LeastNumberOfFaults", "Reports")</li>
                                </ul>
                                </li>
                        </ul>
                    </li>
                     }
                </ul>
                <div style="float: right">@Html.Partial("_LogOnPartial")</div>
            </nav>
        </div>
    </header>
    <!-- MAIN -->
    <div id="main">
        <div class="wrapper clearfix">
            <!-- page content -->
            <div id="page-content" class="clearfix">
                <!-- fullwidth content -->
                <div class="fullwidth-content">
                    <h2 class="page-heading">
                        <span>@ViewBag.Title</span></h2>
                    @RenderBody()
                </div>
                <!-- ends fullwidth content -->
            </div>
            <!--  page content-->
        </div>
    </div>
    <!-- ENDS MAIN -->
    <footer>
        <div class="wrapper">
            <div class="footer-bottom">
                <div class="left">
                    Website Made By Clementina Cassar ©</div>
            </div>
        </div>
    </footer>
</body>
</html>

Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "UserAuthentication") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "Login", "UserAuthentication") ]
    
}

 @if (Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Admin") || HttpContext.Current.User.IsInRole("User"))
 {
@Html.ActionLink("Shopping Cart", "ShoppingCart", "ShoppingCart")   <br />
 }